env:
  node: true
  es2023: true # Node 18

root: true

reportUnusedDisableDirectives: true

parserOptions:
  ecmaVersion: 2022 # Node 18
  project: tsconfig.json
  lib: 2023 # Node 18

extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:github/recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:@stylistic/recommended-extends

ignorePatterns:
  - dist/

parser: "@typescript-eslint/parser"

plugins:
  - "@annangela/prefer-reflect"
  - prefer-arrow-functions
  - "@stylistic"
  - "@stylistic/migrate"
  - "@typescript-eslint"

rules:
  "@annangela/prefer-reflect/prefer-reflect": error
  prefer-arrow-functions/prefer-arrow-functions:
    - error
    - classPropertiesAllowed: true
      disallowPrototype: true
      returnStyle: implicit
      singleReturnOnly: false
  logical-assignment-operators: error
  no-new-func: error
  no-object-constructor: error
  no-new-wrappers: error
  no-var: error
  prefer-const: error
  no-extra-parens: error
  no-misleading-character-class: error
  no-template-curly-in-string: error
  require-atomic-updates: error
  curly: error
  indent:
    - 2
    - 4
    - SwitchCase: 1
  linebreak-style:
    - 0
    - windows
  no-console:
    - 0
  no-unused-vars:
    - 1
    - varsIgnorePattern: ^_
  no-redeclare:
    - 1
  no-unreachable:
    - 1
  no-inner-declarations:
    - 0
  comma-dangle:
    - 1
    - always-multiline
  eqeqeq: error
  dot-notation: error
  no-else-return: error
  no-extra-bind: error
  no-labels: error
  no-floating-decimal: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers: off
  no-multi-spaces: error
  no-param-reassign: error
  strict:
    - error
    - global
  quotes:
    - 1
    - double
    - avoidEscape: true
  quote-props:
    - 1
    - as-needed
    - keywords: true
      unnecessary: true
      numbers: false
  no-empty:
    - error
    - allowEmptyCatch: true
  arrow-spacing:
    - error
    - before: true
      after: true
  prefer-arrow-callback: error
  prefer-spread: error
  prefer-template: error
  prefer-rest-params: error
  prefer-exponentiation-operator: error
  require-await: error
  arrow-parens: error
  no-use-before-define: error

  camelcase: error
  "@typescript-eslint/array-type":
    - error
    - default: array
  "@typescript-eslint/await-thenable": error
  "@typescript-eslint/ban-ts-comment": error
  "@typescript-eslint/consistent-type-assertions": error
  "@typescript-eslint/explicit-function-return-type":
    - error
  "@typescript-eslint/explicit-member-accessibility":
    - error
  "@stylistic/function-call-spacing":
    - error
    - never
  "@typescript-eslint/no-array-constructor": error
  "@typescript-eslint/no-empty-interface": error
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-extraneous-class": error
  "@typescript-eslint/no-for-in-array": error
  "@typescript-eslint/no-inferrable-types": error
  "@typescript-eslint/no-misused-new": error
  "@typescript-eslint/no-namespace": error
  "@typescript-eslint/no-non-null-assertion": error
  "@typescript-eslint/no-require-imports": error
  "@typescript-eslint/no-unnecessary-qualifier": error
  "@typescript-eslint/no-unnecessary-type-assertion": error
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/no-useless-constructor": error
  "@typescript-eslint/no-var-requires": error
  "@typescript-eslint/prefer-for-of": error
  "@typescript-eslint/prefer-function-type": error
  "@typescript-eslint/prefer-includes": error
  "@typescript-eslint/prefer-readonly": error
  "@typescript-eslint/prefer-string-starts-ends-with": error
  "@typescript-eslint/promise-function-async": error
  "@typescript-eslint/require-array-sort-compare": error
  "@typescript-eslint/restrict-plus-operands": error
  "@stylistic/semi": error
  "@typescript-eslint/space-before-function-paren": error
  "@typescript-eslint/type-annotation-spacing": error
  "@typescript-eslint/unbound-method": error
